import { PHASE_PRODUCTION_BUILD, PHASE_PRODUCTION_SERVER } from "next/constants.js";

/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };

// Locally, `next dev` and `next build` both default to writing into the
// same `.next/` folder. Running a production build while a dev server is
// live (e.g. to verify a change) makes both processes read/write/prune the
// same webpack cache concurrently, which reliably corrupts it—symptoms
// range from stale 404s to a dev server crashing with "Cannot find module
// './XXXX.js'". Giving production builds their own directory locally means
// the two can never collide, permanently ruling out this failure mode.
//
// This must NOT apply on Vercel: its build pipeline expects the default
// ".next" output (it looks for ".next/routes-manifest.json" post-build) and
// doesn't resolve a custom distDir from a phase-conditional config
// function, so overriding it there breaks deployment outright. Gating on
// `process.env.VERCEL` seemed like the obvious signal, but this project's
// .env.local was generated by `vercel env pull`, which snapshots
// VERCEL="1" into it—so a plain local build would ALSO look like Vercel and
// silently skip the fix. `CI` is the reliable signal instead: Vercel's
// build container sets it at the platform level, but it isn't a
// project-configurable env var, so `vercel env pull` never captures it into
// .env.local (verified: absent from this project's pulled snapshot).
export default (phase) => {
  const isCI = !!process.env.CI;
  if (!isCI && (phase === PHASE_PRODUCTION_BUILD || phase === PHASE_PRODUCTION_SERVER)) {
    return { ...nextConfig, distDir: ".next-build" };
  }
  return nextConfig;
};
