"use client";

import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Activity, Apple, BookOpen, BrainCircuit, ChevronDown, FileQuestion, GraduationCap, Heart, HeartPulse, Layers3, MessageCircle, Microscope, Orbit, PlayCircle, Quote, Rocket, ShieldCheck, Smartphone, Sparkles, WandSparkles } from "lucide-react";
import { DashboardMockup, AIChat } from "@/components/dashboard";
import { Logo, Navigation } from "@/components/navigation";
import { CheckLine, Counter, PrimaryButton, Reveal, VideoButton } from "@/components/ui";

const features = [
  [BrainCircuit, "Your AI study partner", "Get clear explanations, helpful hints, and a plan whenever you need one.", "bg-[#e2f5f3] text-teal-700"],
  [Layers3, "Notes that work harder", "Turn any notes into intelligent flashcards and active-recall practice.", "bg-[#f1edff] text-violet-600"],
  [Orbit, "A path made for you", "Studium adapts to your goals, pace, and the places you need help most.", "bg-[#fff3dd] text-amber-600"],
  [FileQuestion, "Practice with purpose", "Build confidence with custom questions and feedback that teaches.", "bg-[#e8f1ff] text-blue-600"],
  [GraduationCap, "See real progress", "A simple, beautiful picture of what you know and what comes next.", "bg-[#ffeaf0] text-rose-600"],
  [MessageCircle, "Feedback, instantly", "Get unstuck in the moment instead of waiting for the next class.", "bg-[#e8f8ed] text-emerald-600"]
] as const;
const faqs = [["What is Studium?", "Studium is an AI-powered learning workspace that helps you understand material, remember it longer, and see exactly how you are progressing."], ["Can I try it before paying?", "Absolutely. Start with the free plan and explore the essentials. You can upgrade whenever you need more study power."], ["What subjects can I use it for?", "Anything you are learning—from sciences and languages to law, history, and professional qualifications. Upload your own materials or start with a subject."], ["Is my study material private?", "Yes. Your notes and learning data are protected with industry-standard security and are never sold to third parties."]];

export default function Home() {
  return <main id="home" className="overflow-hidden"><Navigation /><Hero /><Trust /><ImmersiveContent /><Features /><LearningShowcase /><HowItWorks /><DashboardSection /><Stats /><Testimonials /><Pricing /><FAQ /><CTA /><DownloadApps /><Footer /></main>;
}
function Hero() { return <section className="relative pt-32 sm:pt-40"><div className="dot-grid absolute inset-x-0 top-0 -z-10 h-[540px] opacity-45 [mask-image:linear-gradient(to_bottom,black,transparent)]" /><div className="absolute left-1/2 top-28 -z-20 h-80 w-[min(800px,100vw)] -translate-x-1/2 rounded-full bg-teal-100/60 blur-[90px]" /><div className="container-page"><div className="mx-auto max-w-3xl text-center"><Reveal><span className="eyebrow"><Sparkles size={13} />The intelligent way to learn</span></Reveal><Reveal delay={.08}><h1 className="display mt-6 text-5xl leading-[.98] sm:text-7xl">Study smarter.<br /><span className="text-teal-500">Learn deeper.</span></h1></Reveal><Reveal delay={.15}><p className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-slate-500 sm:text-lg">Everything you need to master medicine in one place—from AI-powered learning and organized notes to community flashcards, quizzes, and real clinical cases.</p></Reveal><Reveal delay={.22} className="mt-8 flex flex-col items-center justify-center gap-2 sm:flex-row"><PrimaryButton className="w-full sm:w-auto">Start learning for free</PrimaryButton><VideoButton /></Reveal></div><Reveal delay={.18} className="relative mt-14 pb-5 sm:mt-16"><div className="absolute -left-2 top-24 hidden rounded-2xl border border-white bg-white/90 p-3 shadow-lift backdrop-blur md:block float"><div className="flex items-center gap-2"><div className="text-lg">🔥</div><div><p className="text-[10px] font-extrabold">12 day streak</p><p className="text-[9px] text-slate-400">You&apos;re on a roll!</p></div></div></div><DashboardMockup hero /></Reveal></div></section>; }
function Trust() { return <section className="border-y border-slate-100 bg-white py-7"><div className="container-page flex flex-col items-center gap-4 sm:flex-row sm:justify-between"><p className="text-xs font-bold uppercase tracking-[.13em] text-slate-400">Built for learners at</p><div className="flex w-full justify-around gap-4 text-sm font-extrabold text-slate-300 sm:w-auto sm:gap-10"><span>brighton</span><span>northstar</span><span>credo</span><span>COLLEGE</span></div></div></section>; }
function ImmersiveContent() { return <section className="container-page pb-10 pt-20 sm:pb-12 sm:pt-24"><div className="grid items-center gap-10 overflow-hidden rounded-[30px] border border-teal-100 bg-[#f3fbfa] p-7 sm:p-10 lg:grid-cols-[1.1fr_.9fr] lg:p-12"><Reveal><span className="eyebrow">Built for the real world</span><h2 className="display mt-5 max-w-xl text-4xl leading-tight sm:text-5xl">Immerse yourself in real-world content.</h2><p className="mt-5 max-w-xl text-base leading-relaxed text-slate-500">Study with real medical cases, diagnostic challenges, anatomy, and clinical reasoning instead of memorizing isolated facts.</p></Reveal><Reveal delay={.12}><div className="grid grid-cols-2 gap-3"><div className="col-span-2 flex items-center gap-4 rounded-2xl bg-ink p-5 text-white shadow-soft"><span className="grid h-11 w-11 place-items-center rounded-xl bg-teal-400 text-teal-950"><HeartPulse size={22} /></span><div><p className="text-xs font-extrabold">Clinical case of the day</p><p className="mt-1 text-[10px] text-slate-300">Chest pain · Assess, reason, decide</p></div></div><div className="rounded-2xl border border-teal-100 bg-white p-4"><Microscope size={20} className="text-teal-600" /><p className="mt-5 text-xs font-extrabold">Explore anatomy</p><p className="mt-1 text-[10px] text-slate-400">See systems in context</p></div><div className="rounded-2xl border border-teal-100 bg-white p-4"><BrainCircuit size={20} className="text-violet-500" /><p className="mt-5 text-xs font-extrabold">Think clinically</p><p className="mt-1 text-[10px] text-slate-400">Build diagnostic instinct</p></div></div></Reveal></div></section>; }
function Features() { return <section id="features" className="container-page pb-24 pt-12 sm:pb-32 sm:pt-16"><Reveal className="max-w-xl"><span className="eyebrow">Made to help you thrive</span><h2 className="display mt-5 text-4xl leading-tight sm:text-5xl">Everything you need to learn with confidence.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, description, color], i) => <Reveal key={title} delay={i * .05}><motion.article whileHover={{ y: -6 }} className="group h-full rounded-3xl border border-slate-100 bg-white p-6 shadow-soft transition-shadow hover:shadow-lift"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${color}`}><Icon size={21} /></span><h3 className="mt-6 text-lg font-extrabold tracking-tight">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-500">{description}</p><div className="mt-5 h-px w-0 bg-teal-300 transition-all duration-300 group-hover:w-9" /></motion.article></Reveal>)}</div></section>; }
function LearningShowcase() {
  return (
    <section className="relative overflow-hidden bg-[#f3fbfa] py-24 sm:py-32">
      <div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_center,rgba(126,211,209,.32),transparent_66%)]" />
      <div className="container-page relative grid items-center gap-14 lg:grid-cols-[.95fr_1.05fr] lg:gap-20">
        <Reveal className="order-2 lg:order-1">
          <div className="relative mx-auto w-[260px] sm:w-[300px]">
            <div className="absolute -left-20 top-20 h-32 w-32 rounded-full bg-teal-200/70 blur-2xl" />
            <div className="absolute -right-12 bottom-20 h-28 w-28 rounded-full bg-teal-100 blur-2xl" />
            <motion.div animate={{ y: [0, -8, 0] }} transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }} className="relative overflow-hidden rounded-[38px] border-[7px] border-ink bg-white p-3 shadow-[0_28px_55px_-18px_rgba(15,80,80,.4)]">
              <div className="mx-auto h-5 w-20 rounded-b-xl bg-ink" />
              <div className="px-2 pb-4 pt-4">
                <div className="flex items-center justify-between"><p className="text-[10px] font-extrabold text-ink">Medical revision</p><span className="text-[9px] font-bold text-teal-600">7 / 12</span></div>
                <div className="mt-4 overflow-hidden rounded-2xl border border-teal-100 bg-[#effbfa]">
                  <div className="flex h-28 items-center justify-center bg-[radial-gradient(circle_at_center,#d8f4f1,transparent_70%)]"><div className="relative grid h-16 w-16 place-items-center rounded-full border-4 border-teal-400/40 bg-white text-teal-600 shadow-sm"><HeartPulse size={31} /><span className="absolute -right-1 -top-1 grid h-5 w-5 place-items-center rounded-full bg-teal-500 text-white"><Activity size={10} /></span></div></div>
                  <div className="bg-white p-3"><p className="text-[9px] font-bold text-slate-400">CARDIOLOGY</p><p className="mt-1 text-xs font-extrabold leading-snug">What does the mitral valve do?</p></div>
                </div>
                <div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl border border-slate-100 p-2.5"><Microscope size={15} className="text-violet-500" /><p className="mt-2 text-[9px] font-extrabold">Anatomy</p></div><div className="rounded-xl border border-slate-100 p-2.5"><BrainCircuit size={15} className="text-teal-600" /><p className="mt-2 text-[9px] font-extrabold">Recall</p></div></div>
              </div>
            </motion.div>
            <motion.div animate={{ y: [0, 8, 0] }} transition={{ duration: 4.5, repeat: Infinity, ease: "easeInOut", delay: .6 }} className="absolute -right-16 top-32 rounded-2xl border border-white bg-white/95 p-3 shadow-lift"><p className="text-[9px] font-extrabold text-teal-700">+20 XP</p><p className="mt-1 text-[8px] text-slate-400">Great recall!</p></motion.div>
          </div>
        </Reveal>
        <Reveal delay={.12} className="order-1 max-w-xl lg:order-2">
          <span className="eyebrow">Study smarter, naturally</span>
          <h2 className="display mt-5 text-4xl leading-tight sm:text-5xl">Learn the Way Your Brain Was Designed To.</h2>
          <p className="mt-5 max-w-lg text-base leading-relaxed text-slate-500">Forget endless memorization. Studium uses an immersive, science-backed learning approach that helps you understand and retain information naturally.</p>
          <PrimaryButton className="mt-8">Get started for free now</PrimaryButton>
        </Reveal>
      </div>
    </section>
  );
}
function HowItWorks() { const steps = [["01", "Make it yours", "Create your account, add your subjects, and tell Studium what success looks like."], ["02", "Bring your materials", "Upload notes, paste a topic, or pick something new to learn."], ["03", "Learn in your flow", "Get a personalized plan, sharp explanations, and the right questions."], ["04", "Watch yourself grow", "See your knowledge compound, one small win at a time."]]; return <section id="how-it-works" className="bg-ink py-24 text-white sm:py-32"><div className="container-page"><Reveal><span className="eyebrow border-white/10 bg-white/5 text-teal-300">A simpler study system</span><div className="mt-5 flex flex-col justify-between gap-5 md:flex-row"><h2 className="display max-w-lg text-4xl leading-tight text-white sm:text-5xl">From first thought to real understanding.</h2><p className="max-w-xs self-end text-sm leading-relaxed text-slate-300">No more trying to make one-size-fits-all methods fit you.</p></div></Reveal><div className="mt-14 grid gap-4 md:grid-cols-4">{steps.map(([number, title, text], i) => <Reveal key={number} delay={i * .1}><div className="relative h-full rounded-2xl border border-white/10 bg-white/[.04] p-5"><span className="text-sm font-extrabold text-teal-300">{number}</span>{i < 3 && <div className="absolute -right-3 top-10 z-10 hidden h-px w-6 bg-teal-400/50 md:block" />}<h3 className="mt-10 text-lg font-extrabold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-300">{text}</p></div></Reveal>)}</div></div></section>; }
function DashboardSection() { return <section className="container-page py-24 sm:py-32"><div className="grid items-center gap-14 lg:grid-cols-[.78fr_1.22fr]"><Reveal><span className="eyebrow">Clarity, at a glance</span><h2 className="display mt-5 text-4xl leading-tight sm:text-5xl">Know where you are. Know what&apos;s next.</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-slate-500">A calm, focused home for your learning. Your goals, plans, study streaks, and wins—all in one place.</p><ul className="mt-7 space-y-3"><CheckLine>Gentle daily goals that add up</CheckLine><CheckLine>Insights that keep you motivated</CheckLine><CheckLine>One place for every subject</CheckLine></ul><a href="#pricing" className="mt-8 inline-flex items-center gap-1 text-sm font-extrabold text-teal-600 hover:text-teal-700">Explore the dashboard <span>→</span></a></Reveal><Reveal delay={.12}><DashboardMockup /></Reveal></div></section>; }
function Stats() { return <section className="border-y border-teal-100 bg-teal-50/60 py-14"><div className="container-page grid grid-cols-2 gap-x-7 gap-y-9 md:grid-cols-4"><Counter value={125000} suffix="+" label="students learning" /><Counter value={4} suffix="M+" label="study hours saved" /><Counter value={38} suffix="M+" label="questions answered" /><Counter value={94} suffix="%" label="feel more confident" /></div></section>; }
function Testimonials() { const quotes = [["Studium makes revision feel so much less overwhelming. It knows when to push me and when to slow down.", "Sofia L.", "Medical student"], ["It turned a mountain of notes into a plan I could actually follow. My confidence has changed completely.", "Daniel K.", "A-level student"], ["The flashcards and feedback are exactly what I needed. I&apos;m finally studying smarter, not longer.", "Priya R.", "Law student"]]; return <section className="container-page py-24 sm:py-32"><Reveal className="text-center"><span className="eyebrow">Loved by learners</span><h2 className="display mt-5 text-4xl sm:text-5xl">Small moments. Big shifts.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-3">{quotes.map(([quote, name, role], i) => <Reveal key={name} delay={i*.08}><article className="flex h-full flex-col rounded-3xl border border-slate-100 bg-white p-6 shadow-soft"><Quote size={24} className="text-teal-300" fill="currentColor" /><p className="mt-5 flex-1 text-base font-semibold leading-relaxed tracking-tight text-slate-700">“{quote}”</p><div className="mt-7 flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-full text-xs font-extrabold ${["bg-teal-100 text-teal-700", "bg-violet-100 text-violet-700", "bg-amber-100 text-amber-700"][i]}`}>{name.split(" ").map(x=>x[0]).join("")}</span><div><p className="text-xs font-extrabold">{name}</p><p className="text-[10px] text-slate-400">{role}</p></div></div></article></Reveal>)}</div></section>; }
function Pricing() { const plans = [{ name:"Starter", price:"0", text:"A better way to begin.", items:["AI study help", "3 subjects", "Essential flashcards"] }, { name:"Plus", price:"12", text:"For focused learners.", items:["Unlimited subjects", "Personal learning plans", "Advanced analytics", "Practice exams"], popular:true }, { name:"Pro", price:"24", text:"For big academic goals.", items:["Everything in Plus", "Priority AI support", "Deep-dive insights", "Early access features"] }]; return <section id="pricing" className="bg-[#f5fafa] py-24 sm:py-32"><div className="container-page"><Reveal className="text-center"><span className="eyebrow">Simple, honest pricing</span><h2 className="display mt-5 text-4xl sm:text-5xl">Invest in your future self.</h2><p className="mt-4 text-sm text-slate-500">Start free. Upgrade when your ambition needs more room.</p></Reveal><div className="mx-auto mt-12 grid max-w-5xl gap-4 md:grid-cols-3">{plans.map((plan, i) => <Reveal key={plan.name} delay={i*.08}><motion.div whileHover={{ y: -7 }} className={`relative h-full rounded-3xl border p-6 ${plan.popular ? "border-teal-500 bg-ink text-white shadow-lift" : "border-slate-100 bg-white shadow-soft"}`}>{plan.popular && <span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-teal-400 px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-teal-950">Most popular</span>}<h3 className="text-lg font-extrabold">{plan.name}</h3><p className={`mt-2 h-10 text-xs ${plan.popular ? "text-slate-300" : "text-slate-500"}`}>{plan.text}</p><div className="mt-5 flex items-baseline"><span className={`display text-4xl ${plan.popular ? "!text-white" : ""}`}>€{plan.price}</span><span className={`ml-1 text-xs ${plan.popular ? "text-slate-300" : "text-slate-400"}`}>/ month</span></div><a href="#" className={`mt-6 block rounded-full py-3 text-center text-sm font-extrabold transition ${plan.popular ? "bg-teal-400 text-teal-950 hover:bg-teal-300" : "bg-teal-50 text-teal-700 hover:bg-teal-100"}`}>{plan.price === "0" ? "Get started" : "Start free trial"}</a><ul className="mt-7 space-y-3">{plan.items.map(x => <li key={x} className={`flex gap-2 text-xs font-medium ${plan.popular ? "text-slate-200" : "text-slate-600"}`}><ShieldCheck size={15} className="shrink-0 text-teal-500" />{x}</li>)}</ul></motion.div></Reveal>)}</div></div></section>; }
function FAQ() { const [open, setOpen] = useState(0); return <section id="faq" className="container-page py-24 sm:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><Reveal><span className="eyebrow">Questions, answered</span><h2 className="display mt-5 text-4xl leading-tight sm:text-5xl">A few things you might be wondering.</h2><p className="mt-5 text-sm leading-relaxed text-slate-500">Still curious? Our friendly team is always happy to help.</p><a href="mailto:hello@studium.app" className="mt-6 inline-block text-sm font-extrabold text-teal-600">Talk to us →</a></Reveal><div>{faqs.map(([question, answer], i) => <div key={question} className="border-b border-slate-200"><button onClick={() => setOpen(i === open ? -1 : i)} className="flex w-full items-center justify-between py-5 text-left text-sm font-extrabold"><span>{question}</span><ChevronDown size={18} className={`text-teal-600 transition-transform ${open === i ? "rotate-180" : ""}`} /></button><AnimatePresence initial={false}>{open === i && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><p className="max-w-xl pb-5 text-sm leading-relaxed text-slate-500">{answer}</p></motion.div>}</AnimatePresence></div>)}</div></div></section>; }
function CTA() { return <section className="container-page pb-24 sm:pb-32"><Reveal><div className="relative overflow-hidden rounded-[34px] bg-teal-600 px-7 py-16 text-center text-white sm:px-16 sm:py-20"><div className="absolute -left-16 -top-16 h-56 w-56 rounded-full bg-teal-400/50 blur-2xl" /><div className="absolute -bottom-20 -right-10 h-56 w-56 rounded-full bg-teal-800/50 blur-2xl" /><div className="relative"><Rocket className="mx-auto text-teal-100" size={30} /><h2 className="display mt-5 text-4xl leading-tight text-white sm:text-5xl">Your next breakthrough<br />starts here.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-relaxed text-teal-100">Make your study time feel lighter, sharper, and entirely your own.</p><PrimaryButton className="mt-8 !bg-white !text-teal-700 hover:!bg-teal-50">Start learning for free</PrimaryButton></div></div></Reveal></section>; }
function DownloadApps() { return <section className="border-t border-slate-100 bg-white py-16 sm:py-20"><div className="container-page"><Reveal><div className="flex flex-col items-center justify-between gap-7 rounded-3xl bg-[#f3fbfa] px-6 py-9 text-center sm:px-10 lg:flex-row lg:text-left"><div className="flex max-w-xl items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-teal-500 text-white shadow-soft"><Smartphone size={22} /></span><div><h2 className="display text-2xl">Carry your momentum with you.</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">A spare ten minutes can become your smartest study session. Keep your cards, goals, and AI tutor close—wherever the day takes you.</p></div></div><div className="flex flex-col gap-2 xs:flex-row sm:flex-row"><a href="#" className="flex min-w-[158px] items-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-left text-white transition hover:-translate-y-0.5 hover:bg-slate-800"><Apple size={24} strokeWidth={2.2} fill="currentColor" className="shrink-0 text-white" /><span><span className="block text-[8px] font-medium uppercase tracking-wider text-slate-300">Download on the</span><span className="block text-sm font-bold leading-tight">App Store</span></span></a><a href="#" className="flex min-w-[158px] items-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-left text-white transition hover:-translate-y-0.5 hover:bg-slate-800"><svg aria-hidden="true" viewBox="0 0 34 38" className="h-7 w-7 shrink-0"><path fill="#34A853" d="M3 2.2 20.5 19 3 35.8Z" /><path fill="#4285F4" d="m3 2.2 20.5 12.1-6 4.7Z" /><path fill="#FBBC04" d="m3 35.8 14.5-16 6 4.7Z" /><path fill="#EA4335" d="m23.5 14.3 6.6 3.9a1 1 0 0 1 0 1.6l-6.6 3.9-6-4.7Z" /></svg><span><span className="block text-[8px] font-medium uppercase tracking-wider text-slate-300">Get it on</span><span className="block text-sm font-bold leading-tight">Google Play</span></span></a></div></div></Reveal></div></section>; }
function Footer() { return <footer className="border-t border-slate-100 bg-white py-12"><div className="container-page"><div className="grid gap-10 md:grid-cols-[1.4fr_repeat(3,1fr)]"><div><Logo /><p className="mt-4 max-w-xs text-xs leading-relaxed text-slate-500">A kinder, smarter way to learn. Built around you.</p></div>{[["Product", "Features", "Pricing", "For educators"], ["Resources", "Help centre", "Study guides", "Community"], ["Company", "About", "Careers", "Contact"]].map(([head,...links]) => <div key={head}><p className="text-xs font-extrabold">{head}</p>{links.map(x => <a href={x === "About" ? "/about" : x === "Careers" ? "/careers" : "#"} key={x} className="mt-3 block text-xs text-slate-500 hover:text-teal-600">{x}</a>)}</div>)}</div><div className="mt-12 flex flex-col justify-between gap-4 border-t border-slate-100 pt-6 text-[11px] text-slate-400 sm:flex-row"><p>© 2026 Studium, Inc. All rights reserved.</p><div className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Instagram</a><a href="#">LinkedIn</a></div></div></div></footer>; }
