"use client";

import { motion } from "framer-motion";
import { ArrowUpRight, Bot, CheckCircle2, ChevronRight, Clock3, Flame, MoreHorizontal, Send, Sparkles, Target } from "lucide-react";
import Image from "next/image";

const bars = [40, 64, 48, 82, 66, 92, 74];
export function DashboardMockup({ hero = false }: { hero?: boolean }) {
  return <div className={`relative ${hero ? "mx-auto max-w-[670px]" : ""}`}>
    <div className="absolute -inset-8 -z-10 rounded-[48px] bg-teal-100/70 blur-3xl" />
    <div className="overflow-hidden rounded-[22px] border border-slate-200/80 bg-white shadow-[0_32px_80px_-30px_rgba(15,60,61,.35)]">
      <div className="flex h-11 items-center gap-1.5 border-b bg-slate-50/80 px-4"><i className="h-2 w-2 rounded-full bg-[#ff625b]" /><i className="h-2 w-2 rounded-full bg-[#ffbd44]" /><i className="h-2 w-2 rounded-full bg-[#00ca4e]" /><div className="ml-4 h-5 w-36 rounded-md bg-white" /></div>
      <div className="flex min-h-[330px] sm:min-h-[410px]">
        <aside className="hidden w-40 shrink-0 border-r bg-[#fbfcfc] p-4 sm:block"><div className="mb-7 flex items-center"><Image src="/images/studium-logo-full.png" alt="Studium" width={779} height={303} className="h-4 w-auto object-contain" /></div>{["Overview", "My learning", "Flashcards", "Practice"].map((x, i) => <div key={x} className={`mb-1 rounded-lg px-2 py-2 text-[10px] font-bold ${i === 0 ? "bg-teal-50 text-teal-700" : "text-slate-500"}`}>{x}</div>)}<div className="mt-8 rounded-xl bg-ink p-3 text-white"><div className="text-[9px] font-bold text-teal-300">STUDY STREAK</div><div className="mt-1 flex items-end gap-1 text-xl font-extrabold">12 <Flame size={15} className="mb-1 text-orange-300" fill="currentColor" /></div><div className="mt-1 text-[9px] text-slate-300">Keep it going!</div></div></aside>
        <main className="min-w-0 flex-1 p-4 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold text-teal-600">MONDAY, OCTOBER 14</p><h3 className="mt-1 text-base font-extrabold tracking-tight sm:text-lg">Good morning, Maya <span>✦</span></h3></div><div className="grid h-8 w-8 place-items-center rounded-full bg-teal-100 text-[11px] font-bold text-teal-700">MC</div></div>
          <div className="mt-5 grid grid-cols-3 gap-2 sm:gap-3"><MiniCard icon={<Target size={14} />} title="Daily goal" value="3 / 4" color="bg-teal-50 text-teal-600" /><MiniCard icon={<Clock3 size={14} />} title="Study time" value="1h 24m" color="bg-violet-50 text-violet-500" /><MiniCard icon={<CheckCircle2 size={14} />} title="Lessons" value="12" color="bg-amber-50 text-amber-500" /></div>
          <div className="mt-4 grid gap-4 lg:grid-cols-[1.3fr_.8fr]"><section className="rounded-xl border border-slate-100 p-3 sm:p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold">Your learning rhythm</p><p className="mt-0.5 text-[9px] text-slate-500">This week</p></div><MoreHorizontal size={15} className="text-slate-500" /></div><div className="mt-5 flex h-[85px] items-end justify-between gap-1">{bars.map((h, i) => <div key={i} className="flex flex-1 flex-col items-center gap-1"><motion.div initial={{ height: 0 }} whileInView={{ height: `${h}%` }} transition={{ delay: i * .07, duration: .5 }} className={`w-full rounded-t-md ${i === 5 ? "bg-teal-500" : "bg-teal-100"}`} /><span className="text-[7px] text-slate-500">{["M","T","W","T","F","S","S"][i]}</span></div>)}</div></section><section className="rounded-xl bg-[#f2faf9] p-3 sm:p-4"><Sparkles size={15} className="text-teal-600" /><p className="mt-2 text-[11px] font-extrabold leading-snug">You&apos;re 18% ahead of your weekly pace.</p><button type="button" className="mt-3 cursor-pointer text-[9px] font-bold text-teal-700">View insights <ArrowUpRight className="inline" size={10} /></button></section></div>
          <div className="mt-4 rounded-xl border border-slate-100 p-3 sm:p-4"><div className="flex items-center justify-between"><p className="text-xs font-extrabold">Continue learning</p><button type="button" className="cursor-pointer text-[10px] font-bold text-teal-600">See all</button></div><div className="mt-3 flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-amber-100 text-xs">⚛</div><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-bold">Introduction to Atomic Structure</p><div className="mt-1.5 h-1 w-full overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[68%] rounded-full bg-teal-500" /></div></div><ChevronRight size={15} className="text-slate-500" /></div></div>
        </main>
      </div>
    </div>
    {hero && <motion.div animate={{ y: [0, -10, 0] }} transition={{ duration: 4, repeat: Infinity }} className="absolute -right-5 top-[24%] hidden rounded-2xl border border-white/70 bg-white/90 p-3 shadow-lift backdrop-blur sm:block"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-teal-100 text-teal-600"><Bot size={14} /></span><div><p className="text-[9px] font-extrabold">Ask Studium</p><p className="text-[8px] text-slate-500">Always here to help</p></div></div></motion.div>}
  </div>;
}
function MiniCard({ icon, title, value, color }: { icon: React.ReactNode; title: string; value: string; color: string }) { return <div className="rounded-xl border border-slate-100 bg-white p-2 sm:p-3"><span className={`grid h-6 w-6 place-items-center rounded-lg ${color}`}>{icon}</span><p className="mt-2 truncate text-[8px] font-medium text-slate-500">{title}</p><p className="mt-0.5 text-[11px] font-extrabold">{value}</p></div>; }
export function AIChat() { return <div className="rounded-2xl border border-teal-100 bg-white p-4 shadow-soft"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-teal-500 text-white"><Bot size={16} /></span><div><p className="text-xs font-extrabold">Studium AI</p><p className="text-[10px] text-teal-600">Online now</p></div></div><div className="mt-5 rounded-xl rounded-tl-sm bg-slate-50 p-3 text-xs leading-relaxed text-slate-600">Want to revise photosynthesis? I&apos;ve made a 10-minute recap based on your notes.</div><div className="mt-3 flex items-center rounded-xl border bg-white px-3 py-2 text-[11px] text-slate-500">Ask anything...<Send size={14} className="ml-auto text-teal-500" /></div></div>; }
