// Document-lesson content for "Magnetism & Electromagnetic Phenomena"
// (lib/mcatPath.ts's magnetism-electromagnetic-phenomena LessonContent entry).
// See lib/documentLesson.ts for the shared shape.
import { DocumentLessonContent } from "../documentLesson";

export const magnetismElectromagneticPhenomenaContent: DocumentLessonContent = {
  lessonIntro: {
    description: "Magnetism and electricity are deeply linked: moving charges create magnetic fields, and changing magnetic fields create electric current. This lesson covers the force a magnetic field exerts on moving charges and current-carrying wires, how currents themselves generate magnetic fields, and how induction converts a changing magnetic field into an electric current.",
    objectives: [
      "Calculate the magnetic force on a moving charge and on a current-carrying wire, using the right-hand rule for direction",
      "Describe the magnetic field generated by a current-carrying wire and a solenoid",
      "State Faraday's law and Lenz's law and apply them to predict induced current direction",
      "Explain the relationship between changing magnetic flux and induced EMF"
    ]
  },
  bigPicture: {
    flow: ["Moving charge or current", "Generates a magnetic field around it", "That field can exert a force on other moving charges/currents", "A changing magnetic field induces a new current (Faraday's law)"],
    caption: "Electricity and magnetism form a two-way street: moving charge creates magnetic field, and a changing magnetic field creates current—each direction has its own named law, but they're really one unified phenomenon."
  },
  concepts: [
    {
      number: "01",
      id: "magnetic-force-moving-charges",
      title: "Magnetic Force on Moving Charges and Currents",
      difficulty: "REASON",
      coreIdea: "A magnetic field exerts a force on a moving charge (F = qvB sin θ) or current-carrying wire, with direction found using the right-hand rule; a magnetic field exerts no force on a stationary charge.",
      learn: [
        "The magnetic force on a moving charge, F = qvB sin θ, depends on the charge's velocity, the field strength, and the angle between them—it's zero when the charge moves parallel to the field and maximal when moving perpendicular to it; critically, a magnetic field exerts no force at all on a charge that isn't moving.",
        "The direction of the magnetic force is found with the right-hand rule: point your fingers in the direction of velocity (or current), curl them toward the magnetic field direction, and your thumb points in the direction of the force on a positive charge (reverse the direction for a negative charge)—the force is always perpendicular to both the velocity and the field."
      ],
      mcatConnection: "Because the magnetic force is always perpendicular to velocity, it never does work on a moving charge (only changes its direction, not its speed)—this is a common conceptual question, distinguishing magnetic force from electric force, which can do work.",
      quickCheck: {
        prompt: "A charged particle moves through a uniform magnetic field, experiencing a magnetic force that curves its path into a circle. What happens to the particle's speed as it moves along this circular path?",
        options: ["It increases steadily", "It decreases steadily", "It remains constant, since the magnetic force is always perpendicular to velocity and therefore does no work", "It oscillates between increasing and decreasing"],
        correctIndex: 2,
        explanation: "Because the magnetic force is always perpendicular to the particle's velocity, it can never do work on the particle (W = Fd cos θ = 0 when force and displacement are perpendicular)—the force changes only the direction of motion, not its speed, which is exactly why the path curves into a circle at constant speed."
      },
      keyTakeaway: "Magnetic force on a moving charge (F = qvB sin θ) is found using the right-hand rule, acts only on moving charges, is always perpendicular to velocity, and therefore never does work (never changes speed, only direction)."
    },
    {
      number: "02",
      id: "sources-of-magnetic-fields",
      title: "Sources of Magnetic Fields",
      difficulty: "IDENTIFY",
      coreIdea: "A current-carrying wire generates a circular magnetic field around itself (direction by the right-hand rule); a solenoid (coiled wire) generates a strong, roughly uniform field inside itself, similar to a bar magnet.",
      learn: [
        "A straight current-carrying wire generates a magnetic field that circles around the wire; pointing your right thumb in the direction of conventional current, your curled fingers show the direction the magnetic field circles around the wire at any point.",
        "A solenoid (a wire coiled into a helix) concentrates and aligns these circular fields from each loop, producing a strong, roughly uniform magnetic field inside the coil, directed along its axis—the field pattern outside the solenoid resembles that of a bar magnet, with distinct north and south poles."
      ],
      mcatConnection: "The right-hand rule for a straight wire (curl fingers = field direction, thumb = current direction) is the version most often tested for source fields—it's a different application of the same right-hand-rule tool used for magnetic force, so keep the two uses distinct.",
      quickCheck: {
        prompt: "Current flows upward through a straight vertical wire. Using the right-hand rule, what is the direction of the magnetic field it creates at a point directly to the right of the wire?",
        options: ["Pointing directly away from the wire", "Pointing directly toward the wire", "Pointing into the page", "Pointing out of the page"],
        correctIndex: 3,
        explanation: "Pointing the right thumb upward (the current's direction) and curling the fingers shows the field circling counterclockwise when viewed from above—at a point to the right of the wire, that circular field points out of the page (toward the viewer); this is the standard right-hand rule for a field generated by a current, not the force rule."
      },
      keyTakeaway: "A current-carrying wire generates a circular magnetic field around it (direction from the right-hand rule, curling fingers around the current direction); a solenoid concentrates these fields into a strong, roughly uniform field resembling a bar magnet."
    },
    {
      number: "03",
      id: "electromagnetic-induction",
      title: "Electromagnetic Induction",
      difficulty: "REASON",
      coreIdea: "Faraday's law states that a changing magnetic flux through a loop induces an EMF (voltage); Lenz's law states that the induced current always opposes the change in flux that created it.",
      learn: [
        "Faraday's law states that the induced EMF in a loop is proportional to the rate of change of magnetic flux through it (EMF = -dΦ/dt, where flux Φ depends on field strength, area, and orientation)—flux can change by varying the field strength, the loop's area, or the angle between the field and the loop, and any of these changes induces a current if the loop is part of a closed circuit.",
        "Lenz's law (reflected in the negative sign in Faraday's law) states that the induced current flows in whatever direction creates a magnetic field opposing the change in flux that caused it—this is a direct consequence of energy conservation, since an induced current that reinforced the change instead would create runaway energy from nothing."
      ],
      mcatConnection: "Lenz's law problems are solved by first identifying whether flux through the loop is increasing or decreasing, then determining which direction of induced current would create a field opposing that specific change—working backward from the answer choices to see which is self-consistent is often faster than deriving it from scratch.",
      quickCheck: {
        prompt: "A bar magnet's north pole is pushed toward a wire loop, increasing the magnetic flux through the loop. According to Lenz's law, what does the induced current in the loop do?",
        options: ["It creates a magnetic field that reinforces the increasing flux", "It creates a magnetic field that opposes the increasing flux, effectively repelling the approaching magnet", "No current is induced, since the magnet is not touching the loop", "The current direction is random and cannot be predicted"],
        correctIndex: 1,
        explanation: "Lenz's law requires the induced current to oppose the change in flux that caused it—since flux is increasing as the magnet approaches, the induced current creates a magnetic field opposing that increase, which (by the resulting force) effectively repels the approaching magnet; no physical contact is required for flux to change and induce a current."
      },
      keyTakeaway: "Faraday's law states a changing magnetic flux induces an EMF; Lenz's law states the induced current opposes the change in flux that caused it, consistent with conservation of energy."
    }
  ]
};
