// Document-lesson content for "Oxidative Phosphorylation" (lib/mcatPath.ts's
// oxidative-phosphorylation LessonContent entry)—restructured from that
// same real entry. See lib/documentLesson.ts for the shared shape.
import { DocumentLessonContent } from "../documentLesson";

export const oxidativePhosphorylationContent: DocumentLessonContent = {
  lessonIntro: {
    description: "This is where the vast majority of a cell's ATP is actually made—not by direct synthesis, but by an electrical gradient. This lesson covers the electron transport chain, how that gradient gets converted into ATP by chemiosmosis, and why the whole process depends entirely on oxygen.",
    objectives: [
      "Describe how the electron transport chain builds a proton gradient",
      "Explain chemiosmosis and ATP synthase's role in it",
      "Explain oxygen's role as the final electron acceptor",
      "Explain why NADH yields more ATP than FADH2"
    ]
  },
  bigPicture: {
    flow: ["NADH/FADH2 donate electrons", "ETC pumps protons", "Proton gradient builds", "ATP synthase makes ATP"],
    caption: "Electron flow and ATP synthesis are two separate physical processes linked only by the proton gradient between them—break the link anywhere and both stop."
  },
  concepts: [
    {
      number: "01",
      id: "electron-transport-chain",
      title: "The Electron Transport Chain",
      difficulty: "UNDERSTAND",
      coreIdea: "NADH and FADH2 donate electrons to the electron transport chain, whose complexes pump protons across the inner mitochondrial membrane as electrons flow toward oxygen.",
      learn: [
        "The electron transport chain (ETC), embedded in the inner mitochondrial membrane, consists of four main protein complexes (I-IV). NADH and FADH2, generated by glycolysis and the citric acid cycle, donate their electrons to this chain (NADH at Complex I, FADH2 at Complex II—which is why NADH yields more ATP than FADH2).",
        "As electrons pass through the complexes toward oxygen, the energy released is used to pump protons (H+) from the mitochondrial matrix into the intermembrane space, building up a proton gradient."
      ],
      mcatConnection: "NADH entering at Complex I (earlier) versus FADH2 entering at Complex II (later, skipping Complex I) is the direct mechanistic reason NADH yields more ATP—this cause-and-effect chain is worth being able to explain, not just recall.",
      quickCheck: {
        prompt: "Why does NADH yield more ATP than FADH2 through oxidative phosphorylation?",
        options: ["NADH is a larger molecule", "NADH donates electrons earlier in the chain (Complex I), contributing to proton pumping at more complexes", "FADH2 is not involved in the electron transport chain at all", "NADH bypasses the electron transport chain entirely"],
        correctIndex: 1,
        explanation: "NADH enters at Complex I, so its electrons contribute to proton pumping at more complexes than FADH2's electrons, which enter later at Complex II—molecule size is irrelevant, and FADH2 is very much part of the chain."
      },
      keyTakeaway: "The ETC's four complexes pass electrons from NADH/FADH2 toward oxygen, using the released energy to pump protons and build a gradient—NADH enters earlier than FADH2, yielding more ATP."
    },
    {
      number: "02",
      id: "chemiosmosis-atp-synthase",
      title: "Chemiosmosis and ATP Synthase",
      difficulty: "IDENTIFY",
      coreIdea: "ATP synthase uses the energy of protons flowing back down their gradient to synthesize ATP from ADP and Pi—a process called chemiosmosis.",
      learn: [
        "The proton gradient built by the ETC stores potential energy, since protons naturally want to flow back down their gradient, from the intermembrane space back into the matrix. ATP synthase provides the only channel for that flow, and as protons pass through it, the enzyme physically rotates, using that mechanical energy to synthesize ATP from ADP and Pi—a process called chemiosmosis.",
        "This tightly links electron transport to ATP synthesis: without electron flow, there's no proton gradient, and without a proton gradient, ATP synthase can't make ATP."
      ],
      mcatConnection: "Chemiosmosis is frequently confused with substrate-level phosphorylation—know the distinction: chemiosmosis uses a proton gradient and ATP synthase, while substrate-level phosphorylation (as in glycolysis and the citric acid cycle) directly transfers a phosphate group, no gradient involved.",
      quickCheck: {
        prompt: "What does ATP synthase directly use to synthesize ATP?",
        options: ["Direct transfer of a phosphate from a substrate", "The energy of protons flowing down their concentration gradient", "Electrons donated directly from NADH", "Heat released by the electron transport chain"],
        correctIndex: 1,
        explanation: "ATP synthase harnesses the energy of protons flowing down their gradient (chemiosmosis)—that's distinct from substrate-level phosphorylation, and NADH donates electrons to the chain itself, not directly to ATP synthase."
      },
      keyTakeaway: "Chemiosmosis is ATP synthase converting the proton gradient's potential energy into ATP—a mechanism entirely distinct from substrate-level phosphorylation."
    },
    {
      number: "03",
      id: "yield-regulation",
      title: "Yield and Regulation",
      difficulty: "REASON",
      coreIdea: "Oxygen is the final electron acceptor, forming water; without it, electron flow, the proton gradient, and ATP synthase all halt.",
      learn: [
        "Oxygen serves as the final electron acceptor at the end of the chain (Complex IV), combining with electrons and H+ to form water—without oxygen present, electron flow stops entirely, the proton gradient collapses, and ATP synthase halts, which is why oxidative phosphorylation is strictly aerobic.",
        "Each NADH yields roughly 2.5 ATP and each FADH2 roughly 1.5 ATP through this process, for a theoretical total of around 30-32 ATP per glucose across all of aerobic respiration. Uncoupling proteins can dissipate the proton gradient as heat instead of ATP, which is how brown fat generates warmth."
      ],
      mcatConnection: "Understand this failure chain, not just the fact that oxygen is needed: no oxygen → no final acceptor → electrons back up → no more proton pumping → gradient collapses → ATP synthase stops. Passages often walk you through part of this chain and ask you to complete it.",
      quickCheck: {
        prompt: "A poison blocks Complex IV of the electron transport chain. What is the most likely immediate consequence?",
        options: ["ATP production increases", "Electron flow and proton pumping stop, and ATP synthase activity halts", "Glycolysis stops immediately", "The citric acid cycle speeds up"],
        correctIndex: 1,
        explanation: "Blocking any complex stops electron flow through the chain, collapsing the proton gradient and halting ATP synthase—glycolysis, occurring in the cytoplasm, can continue independently for a time, and the citric acid cycle would slow, not speed up."
      },
      keyTakeaway: "Oxygen accepts electrons at the chain's end, forming water—remove it and electron flow, the proton gradient, and ATP synthase all stop, since oxidative phosphorylation is strictly aerobic."
    }
  ]
};
